# Generated by Django 5.1.2 on 2024-10-19 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='debitcard',
            old_name='expire_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='debitcard',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_number',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 19, 16, 31, 58, 122792, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 19, 16, 32, 29, 295787, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 19, 16, 32, 42, 390577, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='term',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
