# Generated by Django 5.0.6 on 2024-10-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_owner_creditcard_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
